"""
Skill Gap Router - Additional routes for frontend compatibility.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from typing import Optional
from app.core.database import get_db
from app.core.dependencies import get_current_user_id, require_groq
from app.schemas.ai_pages import SkillGapRequest

router = APIRouter()


@router.get("/roles")
def get_roles():
    """Get popular roles for skill gap analysis."""
    from app.services.ai_pages_service import POPULAR_ROLES
    return {"roles": POPULAR_ROLES}


@router.get("/learning-paths")
def get_learning_paths():
    """Return empty list - learning paths are generated by AI per analysis."""
    return {"paths": [], "message": "Learning paths are generated as part of skill gap analysis"}


@router.post("/analyze")
def analyze_skill_gap_legacy(
    data: dict,
    force: bool = Query(default=False),
    user_id: str = Depends(get_current_user_id),
    db: Session = Depends(get_db),
    _: str = Depends(require_groq)
):
    """Legacy endpoint for skill gap analysis (redirects to /ai/skill-gap)."""
    from app.services.ai_pages_service import analyze_skill_gap
    target_role = data.get("target_role", "")
    if not target_role:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail="target_role is required")
    return analyze_skill_gap(db, user_id, target_role, force_recalculate=force)
