"""add_bio_to_users

Revision ID: 3ce4ce217fc6
Revises: add_dashboard_table
Create Date: 2026-05-02 02:24:34.287776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ce4ce217fc6'
down_revision = 'add_dashboard_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_data', 'inr_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('market_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_market_data_not_expired'), table_name='market_data', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('ix_market_data_updated_at'), table_name='market_data')
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.create_index(op.f('ix_market_data_updated_at'), 'market_data', ['updated_at'], unique=False)
    op.create_index(op.f('ix_market_data_not_expired'), 'market_data', ['role', 'location', 'expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.alter_column('market_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_data', 'inr_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
