"""create_ai_and_settings_tables

Revision ID: 4ade65708610
Revises: b6b0e01a6079
Create Date: 2026-04-30 15:10:40.902842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ade65708610'
down_revision = 'b6b0e01a6079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('match_percentage', sa.Integer(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_user_id'), 'ai_recommendations', ['user_id'], unique=False)
    op.create_table('coach_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_uuid', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_sessions_session_uuid'), 'coach_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_coach_sessions_user_id'), 'coach_sessions', ['user_id'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('job_match_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ai_match_score', sa.Integer(), nullable=True),
    sa.Column('match_verdict', sa.String(length=200), nullable=True),
    sa.Column('skill_matches', sa.JSON(), nullable=True),
    sa.Column('scoring_breakdown', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_quick_match', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_history_job_id'), 'job_match_history', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_match_history_user_id'), 'job_match_history', ['user_id'], unique=False)
    op.create_table('market_insights_cache',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_insights_cache_user_id'), 'market_insights_cache', ['user_id'], unique=False)
    op.create_table('skill_gap_analysis',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('readiness_label', sa.String(length=50), nullable=True),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('skills_to_improve', sa.JSON(), nullable=True),
    sa.Column('personalized_learning_path', sa.JSON(), nullable=True),
    sa.Column('gap_summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_analysis_user_id'), 'skill_gap_analysis', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_digest_frequency', sa.String(length=20), nullable=True),
    sa.Column('job_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('application_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('message_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('coach_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_messages_session_id'), 'coach_messages', ['session_id'], unique=False)
    op.create_table('resume_analysis',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resume_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ats_fit_score', sa.Integer(), nullable=True),
    sa.Column('score_feedback', sa.Text(), nullable=True),
    sa.Column('keywords_found', sa.JSON(), nullable=True),
    sa.Column('keywords_missing', sa.JSON(), nullable=True),
    sa.Column('pro_tip', sa.Text(), nullable=True),
    sa.Column('enhancements', sa.JSON(), nullable=True),
    sa.Column('has_analysis', sa.Boolean(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['user_resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_analysis_resume_id'), 'resume_analysis', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_analysis_user_id'), 'resume_analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_analysis_user_id'), table_name='resume_analysis')
    op.drop_index(op.f('ix_resume_analysis_resume_id'), table_name='resume_analysis')
    op.drop_table('resume_analysis')
    op.drop_index(op.f('ix_coach_messages_session_id'), table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_skill_gap_analysis_user_id'), table_name='skill_gap_analysis')
    op.drop_table('skill_gap_analysis')
    op.drop_index(op.f('ix_market_insights_cache_user_id'), table_name='market_insights_cache')
    op.drop_table('market_insights_cache')
    op.drop_index(op.f('ix_job_match_history_user_id'), table_name='job_match_history')
    op.drop_index(op.f('ix_job_match_history_job_id'), table_name='job_match_history')
    op.drop_table('job_match_history')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_coach_sessions_user_id'), table_name='coach_sessions')
    op.drop_index(op.f('ix_coach_sessions_session_uuid'), table_name='coach_sessions')
    op.drop_table('coach_sessions')
    op.drop_index(op.f('ix_ai_recommendations_user_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    # ### end Alembic commands ###
