"""create_profile_tables

Revision ID: 5c655de59a83
Revises: 28465e0e7d80
Create Date: 2026-04-30 13:23:43.428234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c655de59a83'
down_revision = '28465e0e7d80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_education',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_education_user_id'), 'user_education', ['user_id'], unique=False)
    op.create_table('user_experience',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_experience_user_id'), 'user_experience', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.String(length=20), nullable=True),
    sa.Column('target_salary_min', sa.Integer(), nullable=True),
    sa.Column('target_salary_max', sa.Integer(), nullable=True),
    sa.Column('target_salary_currency', sa.String(length=10), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('open_to_relocation', sa.Boolean(), nullable=True),
    sa.Column('notice_period', sa.String(length=50), nullable=True),
    sa.Column('industry_preference', sa.JSON(), nullable=True),
    sa.Column('job_level_preference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_resumes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_resumes_user_id'), 'user_resumes', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Enum('Beginner', 'Intermediate', 'Advanced', 'Expert', name='skill_level_enum'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.add_column('users', sa.Column('headline', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('leetcode', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('portfolio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_uploaded_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'portfolio')
    op.drop_column('users', 'leetcode')
    op.drop_column('users', 'github')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'location')
    op.drop_column('users', 'headline')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_resumes_user_id'), table_name='user_resumes')
    op.drop_table('user_resumes')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_experience_user_id'), table_name='user_experience')
    op.drop_table('user_experience')
    op.drop_index(op.f('ix_user_education_user_id'), table_name='user_education')
    op.drop_table('user_education')
    # ### end Alembic commands ###
