"""add_ai_call_tracking

Revision ID: 8ec0103599e9
Revises: 3ce4ce217fc6
Create Date: 2026-05-02 02:41:24.658799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec0103599e9'
down_revision = '3ce4ce217fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_call_tracking',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ai_call_tracking_date'), 'user_ai_call_tracking', ['date'], unique=False)
    op.create_index(op.f('ix_user_ai_call_tracking_user_id'), 'user_ai_call_tracking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ai_call_tracking_user_id'), table_name='user_ai_call_tracking')
    op.drop_index(op.f('ix_user_ai_call_tracking_date'), table_name='user_ai_call_tracking')
    op.drop_table('user_ai_call_tracking')
    # ### end Alembic commands ###
