"""add_big_opportunities_table

Revision ID: add_big_opportunities
Revises: 4ade65708610
Create Date: 2026-05-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_big_opportunities'
down_revision = '4ade65708610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('big_opportunities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('big_opportunities')
    # ### end Alembic commands ###
